"""
Factory State manager for FlowForge.

Maintains the current simulated production environment including
machines, jobs, current schedule, and schedule state tracking.

Schedule states:
  BASELINE  — The schedule before any disruption
  DISRUPTED — The state if the original schedule were left unchanged after disruption
  RECOVERY  — The optimized schedule generated by FlowForge
"""
from copy import deepcopy

from agents.factory.machine import get_default_machines, get_available_machine_ids, get_machine_energy_map
from agents.factory.job import get_default_jobs, get_active_jobs
from agents.erp.engine import ERPEngine


# Schedule state constants
STATE_BASELINE = "BASELINE"
STATE_DISRUPTED = "DISRUPTED"
STATE_RECOVERY = "RECOVERY"

# Factory status constants
FACTORY_OPERATIONAL = "OPERATIONAL"
FACTORY_DISRUPTED = "DISRUPTED"
FACTORY_RECOVERING = "RECOVERING"
FACTORY_RECOVERED = "RECOVERED"


class FactoryState:
    """
    Centralized factory state container.

    Holds all machines, jobs, schedules (baseline/disrupted/recovery),
    disruption history, ERP operational models, and factory status.
    """

    def __init__(self, machines=None, jobs=None, data_source="Demo Factory"):
        """
        Initialize factory state.

        Args:
            machines: dict of machine configs, or None for default 6 machines
            jobs: list of job dicts, or None for default 12 jobs
            data_source: name of data source (e.g. "Demo Factory" or "factory_schedule.xlsx")
        """
        self.machines = machines if machines is not None else get_default_machines()
        self.jobs = jobs if jobs is not None else get_default_jobs()
        self.data_source = data_source

        # Schedule tracking: baseline is preserved, never overwritten
        self.baseline_schedule = None
        self.disrupted_schedule = None
        self.recovery_schedule = None

        # Current schedule state
        self.schedule_state = STATE_BASELINE

        # Factory operational status
        self.factory_status = FACTORY_OPERATIONAL

        # Disruption history
        self.disruption_history = []

        # Active disruptions (list of disruption dicts)
        self.active_disruptions = []

        # Rich industrial entities
        self.production_lines = []
        self.machine_capabilities = []
        self.production_orders = []
        self.operations = []
        self.materials = []
        self.inventory_items = []
        self.maintenance_records = []
        self.downtime_records = []
        self.energy_observations = []
        self.quality_observations = []
        self.shifts = []
        self.dependencies = []
        self.scenarios = []

        # ERP-lite Operations Engine (Orders, Inventory, Maintenance, Capacity)
        self.erp_engine = ERPEngine(self)

        # Historical audit records with full schedule deltas & decision reports
        self.history_records = []

    def load_normalized_data(self, data: dict, data_source: str = "Industrial Factory"):
        """
        Load complete normalized industrial factory dataset.
        Updates machines, jobs, and all 13 rich operational collections.
        """
        self.data_source = data_source
        if "machines" in data and data["machines"]:
            self.machines = data["machines"]
        if "jobs" in data and data["jobs"]:
            self.jobs = data["jobs"]

        self.production_lines = data.get("production_lines", [])
        self.machine_capabilities = data.get("machine_capabilities", [])
        self.production_orders = data.get("production_orders", [])
        self.operations = data.get("operations", [])
        self.materials = data.get("materials", [])
        self.inventory_items = data.get("inventory", [])
        self.maintenance_records = data.get("maintenance", [])
        self.downtime_records = data.get("downtime", [])
        self.energy_observations = data.get("energy", [])
        self.quality_observations = data.get("quality", [])
        self.shifts = data.get("shifts", [])
        self.dependencies = data.get("dependencies", [])
        self.scenarios = data.get("scenarios", [])
        if "disruptions" in data and data["disruptions"]:
            self.active_disruptions = data["disruptions"]

        self.erp_engine.rebuild_from_state()

    def get_available_machine_ids(self):
        """Return list of machine IDs that are currently available."""
        return get_available_machine_ids(self.machines)

    def get_machine_energy_map(self):
        """Return {machine_id: energy_kwh_per_hour} for all machines."""
        return get_machine_energy_map(self.machines)

    def get_active_jobs(self):
        """Return jobs that are not cancelled."""
        return get_active_jobs(self.jobs)

    def set_baseline_schedule(self, schedule):
        """
        Store the baseline schedule. This is the reference point
        for before/after comparisons.
        """
        self.baseline_schedule = deepcopy(schedule)
        self.schedule_state = STATE_BASELINE

    def set_disrupted_schedule(self, schedule):
        """
        Store what the schedule would look like if left unchanged
        after a disruption (for comparison purposes).
        """
        self.disrupted_schedule = deepcopy(schedule)
        self.schedule_state = STATE_DISRUPTED
        self.factory_status = FACTORY_DISRUPTED

    def set_recovery_schedule(self, schedule):
        """
        Store the optimized recovery schedule generated by FlowForge.
        """
        self.recovery_schedule = deepcopy(schedule)
        self.schedule_state = STATE_RECOVERY
        self.factory_status = FACTORY_RECOVERED

    def get_current_schedule(self):
        """Return the most recent schedule based on current state."""
        if self.schedule_state == STATE_RECOVERY and self.recovery_schedule:
            return self.recovery_schedule
        if self.schedule_state == STATE_DISRUPTED and self.disrupted_schedule:
            return self.disrupted_schedule
        return self.baseline_schedule

    def add_disruption(self, disruption):
        """Record a disruption event."""
        self.active_disruptions.append(disruption)
        self.disruption_history.append(disruption)

    def get_machine_count(self):
        """Return (available_count, total_count)."""
        available = len(self.get_available_machine_ids())
        total = len(self.machines)
        return available, total

    def add_history_record(self, record: dict):
        """Append an audited decision / disruption record to history."""
        self.history_records.insert(0, record)  # Newest first

    def reset(self):
        """
        Reset factory to clean baseline state.
        Restores all machines, jobs, ERP engine, and clears active schedules.
        """
        self.machines = get_default_machines()
        self.jobs = get_default_jobs()
        self.data_source = "Demo Factory"
        self.baseline_schedule = None
        self.disrupted_schedule = None
        self.recovery_schedule = None
        self.schedule_state = STATE_BASELINE
        self.factory_status = FACTORY_OPERATIONAL
        self.active_disruptions = []
        self.erp_engine = ERPEngine(self)
        # Preserve disruption_history and history_records for audit trail

    def to_dict(self):
        """Serialize factory state for API responses."""
        available, total = self.get_machine_count()
        erp_data = self.erp_engine.to_dict()
        return {
            "factory_status": self.factory_status,
            "schedule_state": self.schedule_state,
            "data_source": self.data_source,
            "machines": self.machines,
            "jobs": self.jobs,
            "active_machines": f"{available}/{total}",
            "available_machine_ids": self.get_available_machine_ids(),
            "active_disruptions": self.active_disruptions,
            "baseline_schedule": self.baseline_schedule,
            "disrupted_schedule": self.disrupted_schedule,
            "recovery_schedule": self.recovery_schedule,
            "current_schedule": self.get_current_schedule(),
            # Both keys are included for backward-compat; prefer 'erp_state' in new code
            "erp": erp_data,
            "erp_state": erp_data,
            "history": self.history_records,
            # Rich industrial factory entities
            "production_lines": self.production_lines,
            "machine_capabilities": self.machine_capabilities,
            "production_orders": self.production_orders or erp_data.get("orders", []),
            "operations": self.operations,
            "materials": self.materials,
            "inventory": erp_data.get("inventory", self.inventory_items),
            "maintenance": erp_data.get("maintenance", self.maintenance_records),
            "downtime": self.downtime_records,
            "energy": self.energy_observations,
            "quality": self.quality_observations,
            "shifts": self.shifts,
            "dependencies": self.dependencies,
            "scenarios": self.scenarios,
        }


